let arr=["Ayush","Shubham","rahul"];
console.log(arr.sort());
let nums=[1,2,3,42,112,8,4,223,112];
console.log(nums.sort());
let tech=["c","c++","html","javascript","python","java","c#","sql"];
console.log(tech.reverse().indexOf("javascript"));
console.log("true"=="true");
console.log("true"==="true");
console.log([1]==[1]);
let arr1=[1,2,3];
let arr2= arr1;
console.log(arr1===arr2);
// const g=12;
// g=12.5;
// console.log(g);
const arr4=[1,2,3];
arr4.push(4);
let cars1=["bmw"];
// arr4=cars1;
cars1=arr4;
console.log(cars1);
let arrofarr =[[1,2],[3,4],[5,6]];
console.log(arrofarr.length);
let game1 =[['X',null,'O'],[null,'X',null],['O',null,'X']];
console.log(game1);